# Generated by Django 5.0.4 on 2024-04-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permissions_updated_at', models.DateTimeField()),
                ('guid_password_reset', models.UUIDField(blank=True, null=True, unique=True)),
                ('guid_password_expiry', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
